# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 92, 421, 361))
        self.label.setStyleSheet("background-color: white;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget_Image = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Image.setGeometry(QtCore.QRect(450, 90, 461, 361))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_Image.setFont(font)
        self.tableWidget_Image.setStyleSheet("background-color: white;")
        self.tableWidget_Image.setObjectName("tableWidget_Image")
        self.tableWidget_Image.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Image.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Image.setHorizontalHeaderItem(1, item)
        self.tableWidget_Image.horizontalHeader().setDefaultSectionSize(300)
        self.Browse_Image = QtWidgets.QPushButton(self.centralwidget)
        self.Browse_Image.setGeometry(QtCore.QRect(34, 40, 361, 41))
        self.Browse_Image.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"font-weight: bold;\n"
"border-radius: 10px;\n"
"font-size: 18px;")
        self.Browse_Image.setObjectName("Browse_Image")
        self.Display_Image_From_Database = QtWidgets.QPushButton(self.centralwidget)
        self.Display_Image_From_Database.setGeometry(QtCore.QRect(470, 40, 391, 41))
        self.Display_Image_From_Database.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"font-weight: bold;\n"
"border-radius: 10px;\n"
"font-size: 18px;")
        self.Display_Image_From_Database.setObjectName("Display_Image_From_Database")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        # Ajout d'une ligne pour entrer les coordonnées des seed pixels
        self.seed_pixel_label = QtWidgets.QLabel(self.centralwidget)
        self.seed_pixel_label.setGeometry(QtCore.QRect(34, 460, 150, 30))
        self.seed_pixel_label.setText("Seed Pixels (x, y):")
        self.seed_pixel_label.setObjectName("seed_pixel_label")

        self.seed_pixel_input = QtWidgets.QLineEdit(self.centralwidget)
        self.seed_pixel_input.setGeometry(QtCore.QRect(190, 460, 150, 30))
        self.seed_pixel_input.setObjectName("seed_pixel_input")

        # Ajout d'une ligne pour entrer le seuil
        self.threshold_label = QtWidgets.QLabel(self.centralwidget)
        self.threshold_label.setGeometry(QtCore.QRect(370, 460, 100, 30))
        self.threshold_label.setText("Threshold:")
        self.threshold_label.setObjectName("threshold_label")

        self.threshold_input = QtWidgets.QLineEdit(self.centralwidget)
        self.threshold_input.setGeometry(QtCore.QRect(470, 460, 100, 30))
        self.threshold_input.setObjectName("threshold_input")

        # Ajout d'un bouton pour lancer l'algorithme de croissance de région
        self.apply_region_growing = QtWidgets.QPushButton(self.centralwidget)
        self.apply_region_growing.setGeometry(QtCore.QRect(600, 460, 200, 30))
        self.apply_region_growing.setStyleSheet("background-color: green; color: white; font-weight: bold; border-radius: 10px; font-size: 18px;")
        self.apply_region_growing.setObjectName("apply_region_growing")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_Image.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Image Name"))
        item = self.tableWidget_Image.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Image"))
        self.Browse_Image.setText(_translate("MainWindow", "Browse image"))
        self.Display_Image_From_Database.setText(_translate("MainWindow", "Display from database"))
        
         # Traduction des nouveaux éléments
        self.seed_pixel_label.setText(_translate("MainWindow", "Seed Pixels (x, y):"))
        self.threshold_label.setText(_translate("MainWindow", "Threshold:"))
        self.apply_region_growing.setText(_translate("MainWindow", "Apply Region Growing"))
